name: Self-hosted CI example

on:
  push:
    branches:
      - ubicloud

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Smi
        run: nvidia-smi
      - name: Cuda compiler version
        run: |
          nvcc --version
      - name: Compile example
        run: |
          nvcc -o hello_houston.exe hello_houston.cu
      - name: Run example
        run: |
          ./hello_houston.exe
